epu:
    model_name: "epu_banapple"
    n_classes: 1
    n_subnetworks: 4
    subnetwork: "subnetavg"
    subnetwork_architecture:
        n_classes: 1
        n_blocks: 7
        subnetwork_activation: "tanh"
        block_1:
            in_channels: 1
            out_channels: 32
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: false
            pooling_type: None
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]
        block_2:
            in_channels: 32
            out_channels: 32
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [2, 2]
        block_3:
            in_channels: 32
            out_channels: 64
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: false
            pooling_type: None
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]
        block_4:
            in_channels: 64
            out_channels: 64
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [2, 2]        
        block_5:
            in_channels: 64
            out_channels: 128
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: false
            pooling_type: None
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]
        block_6:
            in_channels: 128
            out_channels: 128
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: false
            pooling_type: None
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]
        block_7:
            in_channels: 128
            out_channels: 128
            n_conv_layers: 1
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [2, 2]
        has_pooling: true
        pooling_type: "globalaveragepooling"
        pooling_kernel_size: [1, 1]
        pooling_stride: [1, 1]
        has_classification_head: true
        classification_head_in_features: 128
    epu_activation: "sigmoid"
    categorical_input_features: ["red-green", 
                                 "blue-yellow", 
                                 "high-frequencies", 
                                 "low-frequencies"]

train_parameters:
    epochs: 250
    learning_rate: 0.001
    batch_size: 32
    shuffle: true
    num_workers: 0
    pin_memory: false
    input_size: 128
    persistent_workers: false
