epu:
    model_name: "kaggle_fake_vs_real"
    n_classes: 1
    n_subnetworks: 4
    subnetwork: "subnetavg"
    subnetwork_architecture:
        n_classes: 1
        n_blocks: 3
        has_pooling: true
        pooling_type: "globalaveragepooling"
        pooling_kernel_size: [1, 1]
        pooling_stride: [1, 1]
        has_contribution_head: true
        block_1:
            in_channels: 1
            out_channels: 32
            n_conv_layers: 2
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: false
            pooling_type: None
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]
        block_2:
            in_channels: 32
            out_channels: 64
            n_conv_layers: 2
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [2, 2]
        block_3:
            in_channels: 64
            out_channels: 128
            n_conv_layers: 3
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]     
        contribution_head:
            in_features: 128
            n_hidden_layers: None
            n_hidden_neurons: None
            hidden_activation: "relu"
            output_activation: "tanh"
    epu_activation: "sigmoid"
    categorical_input_features: ["red-green", 
                                 "blue-yellow", 
                                 "high-frequencies", 
                                 "low-frequencies"]

train_parameters:
    mode: "binary"
    dataset_parser: "folder_parser"
    loss: "binary_cross_entropy"
    epochs: 1000
    learning_rate: 0.001
    image_extension: "jpg"
    batch_size: 64
    shuffle: true
    num_workers: 0
    pin_memory: false
    input_size: 32
    persistent_workers: false
    early_stopping_patience: 25
    dataset_path: "path/to/dataset"
    label_mapping:
        FAKE: 1
        REAL: 0
        
