epu:
    model_name: "kvasirv2"
    n_classes: 8
    n_subnetworks: 4
    subnetwork: "subnetavg"
    subnetwork_architecture:
        n_classes: 8
        n_blocks: 3
        has_pooling: true
        pooling_type: "globalaveragepooling"
        pooling_kernel_size: [1, 1]
        pooling_stride: [1, 1]
        has_contribution_head: true
        block_1:
            in_channels: 1
            out_channels: 64
            n_conv_layers: 2
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: false
            pooling_type: None
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]
        block_2:
            in_channels: 64
            out_channels: 128
            n_conv_layers: 2
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [2, 2]
        block_3:
            in_channels: 128
            out_channels: 256
            n_conv_layers: 2
            kernel_size: [3, 3]
            stride: [1, 1]
            padding: 1
            activation: "relu"
            has_norm: true
            norm_type: "batchnorm2d"
            has_pooling: true
            pooling_type: "maxpooling2d"
            pooling_kernel_size: [2, 2]
            pooling_stride: [1, 1]       
        contribution_head:
            in_features: 256
            n_hidden_layers: None
            n_hidden_neurons: None
            hidden_activation: "relu"
            output_activation: "tanh"
    epu_activation: "softmax"
    categorical_input_features: ["red-green", 
                                 "blue-yellow", 
                                 "high-frequencies", 
                                 "low-frequencies"]

train_parameters:
    mode: "multiclass"
    #dataset_name: "dataset/url" in case of huggingface dataset parser
    dataset_parser: "folder_parser"
    epochs: 1000
    loss: "categorical_cross_entropy"
    image_extension: jpg
    learning_rate: 0.001
    batch_size: 8
    shuffle: true
    num_workers: 0
    pin_memory: false
    input_size: 224
    persistent_workers: false
    early_stopping_patience: 25
    dataset_path: "path/to/dataset"
    label_mapping:
        dyed-lifted-polyps: 0
        dyed-resection-margins: 1
        esophagitis: 2
        normal-cecum: 3
        normal-pylorus: 4
        normal-z-line: 5
        polyps: 6
        ulcerative-colitis: 7
